backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio"
    files:
      - file: "content/portfolio.json"
        label: "Portfolio Projects"
        name: "portfolio"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - label: "ID"
                name: "id"
                widget: "string"

              - label: "Title"
                name: "title"
                widget: "string"

              - label: "Thumbnail"
                name: "thumbnail"
                widget: "image"

              - label: "Short Description"
                name: "short_description"
                widget: "text"

              - label: "Details"
                name: "details"
                widget: "object"
                fields:
                  - label: "Client"
                    name: "client"
                    widget: "string"

                  - label: "Location"
                    name: "location"
                    widget: "string"

                  - label: "Year"
                    name: "year"
                    widget: "string"

                  - label: "Price Range"
                    name: "price_range"
                    widget: "string"

                  - label: "Full Description"
                    name: "full_description"
                    widget: "text"

                  - label: "Images"
                    name: "images"
                    widget: "list"
                    fields:
                      - label: "Image"
                        name: "image"
                        widget: "image"
